# Generated by Django 3.2.7 on 2022-03-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='smallFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('side', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='bigFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('side1', models.CharField(max_length=100, null=True)),
                ('side2', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cart')),
            ],
        ),
    ]
