# Generated by Django 3.2.7 on 2022-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigfood',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smallfood',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
