# Generated by Django 3.2.7 on 2022-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ManyToManyField(null=True, to='app.Food'),
        ),
    ]
