# Generated by Django 3.2.7 on 2022-04-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
