# Generated by Django 3.2.7 on 2022-03-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220323_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='bigFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='smallFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='smallfood',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cart'),
        ),
        migrations.AddField(
            model_name='bigfood',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cart'),
        ),
    ]
