# Generated by Django 3.2.7 on 2022-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='closingTill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('month', models.DateTimeField()),
                ('year', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='dailyLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree1', models.CharField(max_length=100, null=True)),
                ('entree2', models.CharField(max_length=100, null=True)),
                ('side1', models.CharField(max_length=100, null=True)),
                ('side2', models.CharField(max_length=100, null=True)),
                ('side3', models.CharField(max_length=100, null=True)),
                ('bread', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
