# Generated by Django 3.2.7 on 2022-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_closingtill_dailylunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylunch',
            name='dessert',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
