# Generated by Django 3.2.7 on 2022-04-12 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dailylunch_dessert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closingtill',
            name='day',
        ),
        migrations.RemoveField(
            model_name='closingtill',
            name='month',
        ),
        migrations.RemoveField(
            model_name='closingtill',
            name='year',
        ),
        migrations.AddField(
            model_name='closingtill',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
