# Generated by Django 3.2.7 on 2022-04-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
