# Generated by Django 3.2.7 on 2022-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
