# Generated by Django 3.2.7 on 2022-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='noOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='smallfood',
            name='cart',
        ),
        migrations.DeleteModel(
            name='bigFood',
        ),
        migrations.DeleteModel(
            name='smallFood',
        ),
    ]
