# Generated by Django 3.2.7 on 2022-04-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_day'),
        ('app', '0015_auto_20220420_2020'),
    ]

    operations = [
    ]
