# Generated by Django 3.2.7 on 2022-04-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220422_1906'),
        ('app', '0018_auto_20220422_1950'),
    ]

    operations = [
    ]
