# Generated by Django 3.2.7 on 2022-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220425_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='noOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
