# Generated by Django 3.2.7 on 2022-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_sidemodel_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='side1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='side2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='sideModel',
        ),
    ]
