# Generated by Django 3.2.7 on 2022-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_dailylunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree1', models.CharField(max_length=100, null=True)),
                ('entree2', models.CharField(max_length=100, null=True)),
                ('side1', models.CharField(max_length=100, null=True)),
                ('side2', models.CharField(max_length=100, null=True)),
                ('side3', models.CharField(max_length=100, null=True)),
                ('bread', models.CharField(max_length=100, null=True)),
                ('dessert', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
