# Generated by Django 3.2.7 on 2022-04-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220427_1845'),
        ('app', '0033_dailylunch'),
    ]

    operations = [
    ]
