# Generated by Django 3.2.7 on 2022-04-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220427_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartItem',
        ),
    ]
