# Generated by Django 3.2.7 on 2022-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20220429_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
