# Generated by Django 3.2.7 on 2022-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_cartitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
