# Generated by Django 3.2.7 on 2022-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20220502_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
