# Generated by Django 3.2.7 on 2022-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_cartitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='side1',
            field=models.CharField(choices=[('--Choose a Side--', (('corn nuggets', 'Corn Nuggets'), ('tater tots', 'Tater Tots'), ('french fries', 'French Fries'), ('onion rings', 'Onion Rings'), ('fried okra', 'Fried Okra'), ('loaded baked potato', 'Loaded Baked Potato + $2.50'), ('side salad', 'Side Salad + $2.50')))], default='side1', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='side2',
            field=models.CharField(choices=[('--Choose a Side--', (('corn nuggets', 'Corn Nuggets'), ('tater tots', 'Tater Tots'), ('french fries', 'French Fries'), ('onion rings', 'Onion Rings'), ('fried okra', 'Fried Okra'), ('loaded baked potato', 'Loaded Baked Potato + $2.50'), ('side salad', 'Side Salad + $2.50')))], default='side2', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='type',
            field=models.CharField(default='no type', max_length=20),
        ),
    ]
